#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
#ifndef WALLETCOREKIT_SWIFT_H
#define WALLETCOREKIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreData;
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="WalletCoreKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSEntityDescription;
@class NSManagedObjectContext;

SWIFT_CLASS_NAMED("CartCoreData")
@interface CartCoreData : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@class CartItemCoreData;
@class NSSet;

@interface CartCoreData (SWIFT_EXTENSION(WalletCoreKit))
- (void)addItemsObject:(CartItemCoreData * _Nonnull)value;
- (void)removeItemsObject:(CartItemCoreData * _Nonnull)value;
- (void)addItems:(NSSet * _Nonnull)values;
- (void)removeItems:(NSSet * _Nonnull)values;
@end

@class NSString;
@class NSUUID;

@interface CartCoreData (SWIFT_EXTENSION(WalletCoreKit))
@property (nonatomic, copy) NSString * _Nullable cardNumber;
@property (nonatomic, copy) NSString * _Nullable catalogType;
@property (nonatomic, copy) NSUUID * _Nonnull id;
@property (nonatomic, strong) NSSet * _Nullable items;
@end


SWIFT_CLASS_NAMED("CartItemCoreData")
@interface CartItemCoreData : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface CartItemCoreData (SWIFT_EXTENSION(WalletCoreKit))
@property (nonatomic, copy) NSString * _Nullable brand;
@property (nonatomic, copy) NSString * _Nullable catalogId;
@property (nonatomic, copy) NSString * _Nullable categoryId;
@property (nonatomic, copy) NSString * _Nullable catalogCategoryId;
@property (nonatomic, copy) NSUUID * _Nonnull id;
@property (nonatomic) BOOL isBuyNow;
@property (nonatomic) BOOL isDigital;
@property (nonatomic, copy) NSString * _Nullable itemId;
@property (nonatomic, copy) NSString * _Nullable itemType;
@property (nonatomic, copy) NSString * _Nullable notes;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable variantId;
@property (nonatomic, copy) NSString * _Nullable variantName;
@property (nonatomic) double customPrice;
@property (nonatomic) double fixedPrice;
@property (nonatomic) int16_t quantity;
@property (nonatomic, strong) CartCoreData * _Nullable shoppingCart;
@property (nonatomic, copy) NSString * _Nullable targetValue;
@end

@class NSCoder;
@class UITableView;
@class NSIndexPath;
@class UITableViewCell;
@class NSBundle;

SWIFT_CLASS("_TtC13WalletCoreKit31CountryCodePickerViewController") SWIFT_AVAILABILITY(ios,introduced=11.0)
@interface CountryCodePickerViewController : UITableViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)tableView:(UITableView * _Nonnull)tableView titleForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (NSArray<NSString *> * _Nullable)sectionIndexTitlesForTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (nonnull instancetype)initWithStyle:(UITableViewStyle)style SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


SWIFT_AVAILABILITY(ios,introduced=11.0)
@interface CountryCodePickerViewController (SWIFT_EXTENSION(WalletCoreKit))
@end

@class UISearchController;

SWIFT_AVAILABILITY(ios,introduced=11.0)
@interface CountryCodePickerViewController (SWIFT_EXTENSION(WalletCoreKit)) <UISearchResultsUpdating>
- (void)updateSearchResultsForSearchController:(UISearchController * _Nonnull)searchController;
@end


SWIFT_CLASS_NAMED("InAppNotificationCoreData")
@interface InAppNotificationCoreData : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface InAppNotificationCoreData (SWIFT_EXTENSION(WalletCoreKit))
@property (nonatomic, copy) NSString * _Nonnull notificationID;
@property (nonatomic, copy) NSString * _Nullable cardID;
@property (nonatomic, copy) NSString * _Nullable cardNumber;
@property (nonatomic, copy) NSString * _Nullable imageURL;
@property (nonatomic, copy) NSString * _Nullable redirect;
@property (nonatomic, copy) NSString * _Nullable redirectData;
@property (nonatomic, copy) NSString * _Nullable displayType;
@property (nonatomic, copy) NSString * _Nullable displayUnit;
@property (nonatomic) int32_t displayTime;
@property (nonatomic) int32_t count;
@property (nonatomic, copy) NSString * _Nullable firstShownDate;
@property (nonatomic, copy) NSString * _Nullable sessionID;
@end


SWIFT_CLASS_NAMED("InAppNotificationRecordCoreData")
@interface InAppNotificationRecordCoreData : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface InAppNotificationRecordCoreData (SWIFT_EXTENSION(WalletCoreKit))
@property (nonatomic, copy) NSString * _Nonnull notificationID;
@property (nonatomic, copy) NSString * _Nonnull event;
@property (nonatomic, copy) NSString * _Nullable cardID;
@end


SWIFT_CLASS_NAMED("ItemCoreData")
@interface ItemCoreData : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class RedeemInfoCoreData;
@class ShippingAttributeCoreData;

@interface ItemCoreData (SWIFT_EXTENSION(WalletCoreKit))
- (void)addRedeemInfosObject:(RedeemInfoCoreData * _Nonnull)value;
- (void)removeRedeemInfosObject:(RedeemInfoCoreData * _Nonnull)value;
- (void)addRedeemInfos:(NSSet * _Nonnull)values;
- (void)removeRedeemInfos:(NSSet * _Nonnull)values;
- (void)addShippingAttributesObject:(ShippingAttributeCoreData * _Nonnull)value;
- (void)removeShippingAttributesObject:(ShippingAttributeCoreData * _Nonnull)value;
- (void)addShippingAttributes:(NSSet * _Nonnull)values;
- (void)removeShippingAttributes:(NSSet * _Nonnull)values;
@end

@class NSDate;
@class ShoppingCartCoreData;
@class VariantCoreData;

@interface ItemCoreData (SWIFT_EXTENSION(WalletCoreKit))
@property (nonatomic, copy) NSString * _Nonnull catalogId;
@property (nonatomic, copy) NSString * _Nonnull categoryId;
@property (nonatomic, copy) NSString * _Nonnull catalogCategoryId;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSString * _Nullable categoryName;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable categoryShippingMethod;
@property (nonatomic, copy) NSString * _Nullable mId;
@property (nonatomic, strong) NSDate * _Nullable dateAdded;
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic) BOOL isDigital;
@property (nonatomic) BOOL isBuyNow;
@property (nonatomic) BOOL isMultipleVariant;
@property (nonatomic) int32_t maximumQuantityToBuy;
@property (nonatomic, strong) ShoppingCartCoreData * _Nullable shoppingCart;
@property (nonatomic, strong) VariantCoreData * _Nullable variant;
@property (nonatomic, strong) NSSet * _Nullable redeemInfos;
@property (nonatomic, strong) NSSet * _Nullable shippingAttributes;
@property (nonatomic) BOOL isBuyingLimit;
@property (nonatomic, copy) NSString * _Nullable sicepatVendor;
@property (nonatomic, copy) NSString * _Nullable gosendVendor;
@property (nonatomic, copy) NSString * _Nullable brand;
@end




SWIFT_CLASS_NAMED("OtpVerificationCoreData")
@interface OtpVerificationCoreData : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface OtpVerificationCoreData (SWIFT_EXTENSION(WalletCoreKit))
@property (nonatomic, copy) NSString * _Nullable key;
@property (nonatomic, copy) NSString * _Nullable secret;
@property (nonatomic) BOOL isNewUser;
@property (nonatomic) int16_t requestAttempt;
@property (nonatomic) int16_t requestRemaining;
@property (nonatomic) int16_t requestLimit;
@property (nonatomic, copy) NSDate * _Nullable createdAt;
@property (nonatomic, copy) NSDate * _Nullable updatedAt;
@end


SWIFT_CLASS("_TtC13WalletCoreKit17PaymentMethodUtil")
@interface PaymentMethodUtil : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13WalletCoreKit20PhoneNumberFormatter")
@interface PhoneNumberFormatter : NSFormatter
@property (nonatomic) BOOL generatesPhoneNumber;
/// Override region to set a custom region. Automatically uses the default region code.
@property (nonatomic, copy) NSString * _Nonnull defaultRegion;
@property (nonatomic) BOOL withPrefix;
@property (nonatomic, readonly, copy) NSString * _Nonnull currentRegion;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface PhoneNumberFormatter (SWIFT_EXTENSION(WalletCoreKit))
- (NSString * _Nullable)stringForObjectValue:(id _Nullable)obj SWIFT_WARN_UNUSED_RESULT;
- (BOOL)getObjectValue:(id _Nullable * _Nullable)obj forString:(NSString * _Nonnull)string errorDescription:(NSString * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isPartialStringValid:(NSString * _Nonnull * _Nonnull)partialStringPtr proposedSelectedRange:(NSRangePointer _Nullable)proposedSelRangePtr originalString:(NSString * _Nonnull)origString originalSelectedRange:(NSRange)origSelRange errorDescription:(NSString * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC13WalletCoreKit14PhoneNumberKit")
@interface PhoneNumberKit : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



/// Custom text field that formats phone numbers
SWIFT_CLASS("_TtC13WalletCoreKit20PhoneNumberTextField")
@interface PhoneNumberTextField : UITextField <UITextFieldDelegate>
/// Override setText so number will be automatically formatted when setting text by code
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, strong) id <UITextFieldDelegate> _Nullable delegate;
- (void)layoutSubviews;
/// Init with frame
/// \param frame UITextfield F
///
///
/// returns:
/// UITextfield
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
/// Init with coder
/// \param aDecoder decoder
///
///
/// returns:
/// UITextfield
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textFieldShouldBeginEditing:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (void)textFieldDidBeginEditing:(UITextField * _Nonnull)textField;
- (BOOL)textFieldShouldEndEditing:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (void)textFieldDidEndEditing:(UITextField * _Nonnull)textField;
- (void)textFieldDidEndEditing:(UITextField * _Nonnull)textField reason:(UITextFieldDidEndEditingReason)reason SWIFT_AVAILABILITY(tvos,introduced=10.0) SWIFT_AVAILABILITY(ios,introduced=10.0);
- (BOOL)textFieldShouldClear:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
@end



SWIFT_CLASS_NAMED("RedeemInfoCoreData")
@interface RedeemInfoCoreData : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface RedeemInfoCoreData (SWIFT_EXTENSION(WalletCoreKit))
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, strong) ItemCoreData * _Nullable item;
@end


SWIFT_CLASS_NAMED("ShippingAttributeCoreData")
@interface ShippingAttributeCoreData : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface ShippingAttributeCoreData (SWIFT_EXTENSION(WalletCoreKit))
@property (nonatomic) int32_t categoryId;
@property (nonatomic, copy) NSString * _Nullable shippingName;
@property (nonatomic) double maximumDistance;
@property (nonatomic) double minimumPrice;
@property (nonatomic) double pricePerKM;
@property (nonatomic, strong) ItemCoreData * _Nullable item;
@end


SWIFT_CLASS_NAMED("ShoppingCartCoreData")
@interface ShoppingCartCoreData : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class NSIndexSet;
@class NSOrderedSet;

@interface ShoppingCartCoreData (SWIFT_EXTENSION(WalletCoreKit))
- (void)insertObject:(ItemCoreData * _Nonnull)value inItemsAtIndex:(NSInteger)idx;
- (void)removeObjectFromItemsAtIndex:(NSInteger)idx;
- (void)insertItems:(NSArray<ItemCoreData *> * _Nonnull)values atIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)removeItemsAtIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)replaceObjectInItemsAtIndex:(NSInteger)idx withObject:(ItemCoreData * _Nonnull)value;
- (void)replaceItemsAtIndexes:(NSIndexSet * _Nonnull)indexes withItems:(NSArray<ItemCoreData *> * _Nonnull)values;
- (void)addItemsObject:(ItemCoreData * _Nonnull)value;
- (void)removeItemsObject:(ItemCoreData * _Nonnull)value;
- (void)addItems:(NSOrderedSet * _Nonnull)values;
- (void)removeItems:(NSOrderedSet * _Nonnull)values;
@end


@interface ShoppingCartCoreData (SWIFT_EXTENSION(WalletCoreKit))
@property (nonatomic, copy) NSString * _Nullable cardNumber;
@property (nonatomic, copy) NSString * _Nullable cardMerchantCountryCode;
@property (nonatomic, copy) NSString * _Nullable catalogType;
@property (nonatomic, copy) NSString * _Nullable currentLevelName;
@property (nonatomic, copy) NSString * _Nullable programId;
@property (nonatomic) BOOL isPointProgram;
@property (nonatomic) BOOL isStampsProgram;
@property (nonatomic) BOOL isBuyNow;
@property (nonatomic) double pointProgramRate;
@property (nonatomic, copy) NSString * _Nonnull storeId;
@property (nonatomic, copy) NSString * _Nonnull sId;
@property (nonatomic, copy) NSString * _Nonnull areaId;
@property (nonatomic, copy) NSString * _Nonnull latitude;
@property (nonatomic, copy) NSString * _Nonnull longitude;
@property (nonatomic, strong) NSOrderedSet * _Nullable items;
@end


SWIFT_CLASS("_TtC13WalletCoreKit13TadaWalletKit")
@interface TadaWalletKit : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end




SWIFT_CLASS_NAMED("VariantCoreData")
@interface VariantCoreData : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface VariantCoreData (SWIFT_EXTENSION(WalletCoreKit))
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nullable image;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) double price;
@property (nonatomic) double pointProgram;
@property (nonatomic) double weight;
@property (nonatomic) double width;
@property (nonatomic) double height;
@property (nonatomic) double length;
@property (nonatomic) int32_t quantity;
@property (nonatomic, copy) NSString * _Nullable notes;
@property (nonatomic, strong) ItemCoreData * _Nullable item;
@end

@class NSURL;
@class NSData;

/// Overrides the <code>NSUserDefaults</code> class within addition to encrypt and decrypt data. It uses the
/// Advanced Encryption Standard (AES) to encrypt and decrypt data.
/// seealso:
/// https://en.wikipedia.org/wiki/Advanced_Encryption_Standard
SWIFT_CLASS_NAMED("WalletSecureDefaults")
@interface PVSecureDefaults : NSUserDefaults
- (nullable instancetype)initWithSuiteName:(NSString * _Nullable)suitename OBJC_DESIGNATED_INITIALIZER;
- (id _Nullable)objectForKey:(NSString * _Nonnull)defaultName SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)value forKey:(NSString * _Nonnull)defaultName;
- (void)setInteger:(NSInteger)value forKey:(NSString * _Nonnull)defaultName;
- (void)setFloat:(float)value forKey:(NSString * _Nonnull)defaultName;
- (void)setDouble:(double)value forKey:(NSString * _Nonnull)defaultName;
- (void)setBool:(BOOL)value forKey:(NSString * _Nonnull)defaultName;
- (void)setURL:(NSURL * _Nullable)url forKey:(NSString * _Nonnull)defaultName;
- (NSString * _Nullable)stringForKey:(NSString * _Nonnull)defaultName SWIFT_WARN_UNUSED_RESULT;
- (NSArray * _Nullable)arrayForKey:(NSString * _Nonnull)defaultName SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nullable)dictionaryForKey:(NSString * _Nonnull)defaultName SWIFT_WARN_UNUSED_RESULT;
- (NSData * _Nullable)dataForKey:(NSString * _Nonnull)defaultName SWIFT_WARN_UNUSED_RESULT;
- (NSArray<NSString *> * _Nullable)stringArrayForKey:(NSString * _Nonnull)defaultName SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)integerForKey:(NSString * _Nonnull)defaultName SWIFT_WARN_UNUSED_RESULT;
- (float)floatForKey:(NSString * _Nonnull)defaultName SWIFT_WARN_UNUSED_RESULT;
- (double)doubleForKey:(NSString * _Nonnull)defaultName SWIFT_WARN_UNUSED_RESULT;
- (BOOL)boolForKey:(NSString * _Nonnull)defaultName SWIFT_WARN_UNUSED_RESULT;
- (NSURL * _Nullable)URLForKey:(NSString * _Nonnull)defaultName SWIFT_WARN_UNUSED_RESULT;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
